# >>> projects (generated by make workflows) >>>
PROJECTS := ascfix hooks
# <<< projects <<<

.PHONY: help test clean workflows $(addprefix test-,$(PROJECTS)) $(addprefix clean-,$(PROJECTS))

help:
	@echo "make test        - run tests in all projects ($(PROJECTS))"
	@echo "make test-<dir>  - run tests in one project, e.g. make test-hooks"
	@echo "make clean       - clean all projects + __pycache__ sweep"
	@echo "make clean-<dir> - clean one project"
	@echo "make workflows   - regenerate PROJECTS from */Makefile"

test: $(addprefix test-,$(PROJECTS))
	@echo "all tests passed ($(PROJECTS))"

clean: $(addprefix clean-,$(PROJECTS))
	find . -type d -name __pycache__ -prune -exec rm -rf {} +
	@echo "clean done"

test-%:
	$(MAKE) -C $* test

clean-%:
	$(MAKE) -C $* clean

workflows:
	@dirs=$$(for d in $$(grep -lE '^test:' */Makefile 2>/dev/null | xargs -r -n1 dirname | sort); do \
		grep -qE '^clean:' $$d/Makefile 2>/dev/null && echo $$d; \
	done | paste -sd' '); \
	sed -i "s|^PROJECTS := .*|PROJECTS := $$dirs|" Makefile; \
	echo "PROJECTS := $$dirs"
