#!/usr/bin/env python3
import json
import sys
import os
from datetime import datetime

try:
    data = json.load(sys.stdin)
except (json.JSONDecodeError, EOFError, ValueError):
    sys.exit(0)

if not isinstance(data, dict):
    sys.exit(0)

# Output directory for flow reports
REPORT_DIR = os.path.expanduser("~/.claude/flow-reports")
os.makedirs(REPORT_DIR, exist_ok=True)

# Generate report filename
timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
event = data.get("hook_event", "unknown")
report_file = os.path.join(REPORT_DIR, f"{timestamp}-{event}.md")

# Extract session info
session_id = data.get("session_id", "unknown")
cwd = data.get("cwd", os.getcwd())

# Create report content
report = f"""# Flow Report

**Event:** {event}
**Time:** {datetime.now().isoformat()}
**Session:** {session_id}
**Working Directory:** {cwd}

## Summary

Session ended or compacted. Review for patterns:

1. What tasks were attempted?
2. What commands were frequently used?
3. What errors occurred?
4. What could be automated?

## For Learn Agent

Run `/learn` to analyze this session and extract patterns into skills.

---
*Generated by learn.py hook*
"""

try:
    with open(report_file, "w") as f:
        f.write(report)
    # Notify about report
    print(json.dumps({"ok": True, "systemMessage": f"Flow report saved: {report_file}"}))
except OSError:
    # Silent fail - don't break session
    pass

sys.exit(0)
